### PR TITLE
Issue #7 - Employee Validations

### PR DESCRIPTION
**Pull request by ianrbaguio**
Added employee validations using reactive-forms:

- First Name (required, max length of 50)
- Last Name (required, max length of 50)
- Email (required, pattern(email regex))
- Hourly Pay(required, 0-100)

### CODE REVIEW

**Comment by linhub15** [comment]
Can you run `yarn prettier --write src/app/*` for formatting?

**Comment by ianrbaguio** [comment]
> Can you run `yarn prettier --write src/app/*` for formatting?

Okay, I will try it later and let you know

**Comment by linhub15** [comment]
Also, could you add the validation to the `manage-employee.component.ts` form as well?

**Comment by ianrbaguio** [comment]
> Also, could you add the validation to the `manage-employee.component.ts` form as well?

Sure, is this going to be on a different issue/branch/pull request?

**Comment by linhub15** [comment]
> > Also, could you add the validation to the `manage-employee.component.ts` form as well?
> 
> Sure, is this going to be on a different issue/branch/pull request?

It's in the same issue so you could use the same branch. When you push the changes up, it will update this pull request.

**Comment by ianrbaguio** [comment]
> > > Also, could you add the validation to the `manage-employee.component.ts` form as well?
> > 
> > 
> > Sure, is this going to be on a different issue/branch/pull request?
> 
> It's in the same issue so you could use the same branch. When you push the changes up, it will update this pull request.

• Added validations on manage-employee
• Run prettier for formatting

**Pull request merged**
